### PR TITLE
✨ Feat: Support node v4

### PR DESCRIPTION
**Pull request by jacky810124**

### CODE REVIEW

**Comment by kevin940726** [comment]
I don't plan to support Node v4 for now, as this module is intended to use in local development environment only, you probably want to upgrade Node to LTS in most cases. If your project need to support v4, then I suggest using something like nvm to run your code in specific environment.

Also, I pretty sure this is gonna break the tests.... Closing for now, feel free to re-open it if you have a better idea, thanks a lot! :1st_place_medal:

**Comment by jacky810124** [comment]
I've pushed new version in my repo, how do you think?

I misunderstand your code in previous version, I'm sorry about that. But this version I've fixed that bug and can pass the test.

https://github.com/jacky810124/emoji-cz/commit/07829939e1ed7f9c4b96aa163a5a6c577393a82a

**Comment by kevin940726** [comment]
I appreciate your help, but do we really need to support v4? Perhaps you can give me some reason to convince me. :wink:  

Also, I prefer that line to be placed immediately after the function body (before the comment) and follow a blank line.

**Comment by jacky810124** [comment]
Hmm... I can not convince you, I'm using node v6 too....

I find this issue when I use `git cz` in my old computer which installed node v4 only. I think in most cases we do not need to support node v4, but we can use babel to transform ES6 to ES5 for compatibility.

by the way I change the coding style.
https://github.com/jacky810124/emoji-cz/commit/24f16700bff8eaf890e48e09dd749a66d753887a

**Comment by kevin940726** [comment]
I agreed, a better option will be using `babel-preset-env` to transform the code based on environment. For now, I don't see any reason to integrate this module with babel yet. Thanks for your patience and support though, I really appreciate it :smile: .

**Pull request closed without merging**
